"""Skill 执行器家族（R4a 拆分壳）：实现体在 exec_common / exec_spec / exec_tools。

本模块保持既有 import 路径与全部公开符号（含私有符号，测试依赖）不变。
被 monkeypatch 的符号请 patch 调用方所在模块的命名空间（exec_common/exec_spec/exec_tools）。
"""
from src.video_agent.skill_runtime.exec_common import (
    SkillToolResult,
    _resolve_chat_provider,
    _resolve_cascade_fast,
    _executor_thinking,
    _fmt_num,
    _spec_override_clauses,
    _rollback_split_groups,
    _RESP_SCOPE_RE,
    _split_kinds_for_section,
    _prompt_language_rule,
    _style_memory_block,
    _skill_system_prompt,
    _find_uploaded_doc,
    _read_spec_doc,
    _SCRIPT_INJECT_LIMIT,
    _script_inject_limit,
    _build_script_hint,
    _parse_actions_from_text,
    _PROGRESSIVE_FLUSH_N,
    _PROGRESSIVE_FLUSH_SECS,
    _extract_complete_objects,
    _is_truncated,
    _stream_actions_progressive,
    _TITLE_KEYS,
    _action_has_title,
    _apply_actions,
)
from src.video_agent.skill_runtime.exec_spec import (
    _llm_json_call,
    _generate_soft_spec_candidates,
    _candidate_minutes,
    _dedupe_duration_candidates,
    _ASPECT_DIM_HINTS,
    _ASPECT_RATIO_RE,
    _is_aspect_dim,
    _normalize_aspect_candidates,
    _duration_ladder,
    _fill_spec_values,
    _build_state_context,
    _executor_actions_from_llm,
)
from src.video_agent.skill_runtime.exec_tools import (
    SkillToolInput,
    ScriptAnalyzeInput,
    StoryboardSplitInput,
    WriteMediaPromptInput,
    AudioGenerateInput,
    VideoAssemblerInput,
    ScriptAnalyzeTool,
    _KE_TASK,
    _KE_BOUNDARY,
    _KE_SELFCHECK_BOUNDARY,
    _SHOT_TASK,
    _SHOT_BOUNDARY,
    _AUDIO_TASK,
    _AUDIO_BOUNDARY,
    _selfcheck_key_elements,
    _BADGE_CATEGORY_KEYS,
    _badge_category_rank,
    _sort_key_elements_by_badge,
    _run_storyboard_split,
    StoryboardKeyElementsTool,
    StoryboardShotsTool,
    StoryboardAudioTool,
    _coverage_categories,
    _prompt_coverage_note,
    _PROMPT_BATCH_SIZE,
    _PROMPT_BATCH_MAX_TOKENS,
    _PROMPT_MAX_BATCHES,
    _pending_prompt_groups,
    _production_param_note,
    _write_prompt_batch,
    WriteMediaPromptTool,
    AudioGenerateTool,
    VideoAssemblerTool,
    _resolve_section_text,
    SkillSectionRunInput,
    SkillSectionRunTool,
    EXECUTOR_TOOL_CLASSES,
    build_executor_tool,
)
# R4a 补：角标排序家族移入 exec_common 后保持既有引用路径
from src.video_agent.skill_runtime.exec_common import (
    _BADGE_CATEGORY_KEYS,
    _badge_category_rank,
    _sort_key_elements_by_badge,
)
